// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmxowjlykreqnqobvkvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZteG93amx5a3JlcW5xb2J2a3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUxNTU3MDMsImV4cCI6MjA5MDczMTcwM30.nwaTPqG1vCOCu9VD6cHMC0OPCPzvvBJuGV2Cu45KVmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});